### PR TITLE
Dark-light mode added

### PR DESCRIPTION
**Pull request by gulshanjakhon**
Hi @Nktech-Official in this PR i added dark Mode Feature , Please check

### CODE REVIEW

**Comment by gulshanjakhon** [comment]
hi i want little help,
how can i see my update work?
this is easy to me ,so that i can submit my final work to you.
please help!

**Comment by Nktech-Official** [comment]
it's in the readme file

You need Python installed on your system

**Comment by Nktech-Official** [comment]
install python 
open terminal in the Directory 
1. `pip install -r .\requirements.txt`
2. `python app.py`

**Comment by gulshanjakhon** [comment]
i got it
thank you

**Pull request closed without merging**
